// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3sfz6rMBGvdhq6mOaUVtlzY8-yfDictM',
    appId: '1:288652331614:web:7f11ed3db9ed478cb6c2cf',
    messagingSenderId: '288652331614',
    projectId: 'iki-mochi-3bf3b',
    authDomain: 'iki-mochi-3bf3b.firebaseapp.com',
    storageBucket: 'iki-mochi-3bf3b.firebasestorage.app',
    measurementId: 'G-RP9V74CFFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfZLZsBYYdC_zxG9cpnQ7boJR9H-NiGnM',
    appId: '1:288652331614:android:19b20b1a3509391bb6c2cf',
    messagingSenderId: '288652331614',
    projectId: 'iki-mochi-3bf3b',
    storageBucket: 'iki-mochi-3bf3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkN-xf4mI_q7zZ7ypLNTnCJfjr-KLoMR8',
    appId: '1:288652331614:ios:0b1f80b26baaaac3b6c2cf',
    messagingSenderId: '288652331614',
    projectId: 'iki-mochi-3bf3b',
    storageBucket: 'iki-mochi-3bf3b.firebasestorage.app',
    iosBundleId: 'com.example.mochi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkN-xf4mI_q7zZ7ypLNTnCJfjr-KLoMR8',
    appId: '1:288652331614:ios:0b1f80b26baaaac3b6c2cf',
    messagingSenderId: '288652331614',
    projectId: 'iki-mochi-3bf3b',
    storageBucket: 'iki-mochi-3bf3b.firebasestorage.app',
    iosBundleId: 'com.example.mochi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3sfz6rMBGvdhq6mOaUVtlzY8-yfDictM',
    appId: '1:288652331614:web:8f4faf00cd41dd1bb6c2cf',
    messagingSenderId: '288652331614',
    projectId: 'iki-mochi-3bf3b',
    authDomain: 'iki-mochi-3bf3b.firebaseapp.com',
    storageBucket: 'iki-mochi-3bf3b.firebasestorage.app',
    measurementId: 'G-XH65QXQF2J',
  );
}
